Repository validator-labs/validator-plugin-oci, pull requests merged in 2024-08, with the labels that each got.

#238 refactor: derive authn keychain from host
  internal/controller/ocivalidator_controller.go
  pkg/oci/oci_client.go
Labels: enhancement, size:M, lgtm

#240 refactor: support direct rule evaluation
  api/v1alpha1/ocivalidator_types.go
  go.mod
  go.sum
  internal/controller/ocivalidator_controller.go
  internal/controller/ocivalidator_controller_test.go
  pkg/auth/auth.go
  pkg/constants/constants.go
  pkg/oci/oci.go
  pkg/oci/oci_test.go
  pkg/ociclient/oci_client.go
  pkg/ociclient/verifier/verifier.go
  pkg/ociclient/verifier/verifier_test.go
  pkg/validate/validate.go
Labels: enhancement, size:L

#231 chore(main): release 0.0.13
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:M

#248 feat!: default to full layer validation and add support for setting it at rule level with overrides at artifact level
  Makefile
  api/v1alpha1/ocivalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-oci/crds/validation.spectrocloud.labs_ocivalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_ocivalidators.yaml
  config/default/kustomization.yaml
  config/devspace/kustomization.yaml
  config/samples/cosign-pubkeys.yaml
  config/samples/ocivalidator-private-registry.yaml
  config/samples/ocivalidator-public-registry.yaml
  devspace.yaml
  internal/controller/ocivalidator_controller.go
  internal/controller/ocivalidator_controller_test.go
  pkg/oci/oci.go
  pkg/oci/oci_test.go
  pkg/ociclient/oci_client.go
  pkg/validate/validate.go
Labels: size:L, lgtm, new-feature

#243 chore(main): release 0.1.0
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:S

#250 feat: add support for basic and ecr auth for direct invocation
  api/v1alpha1/ocivalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-oci/crds/validation.spectrocloud.labs_ocivalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_ocivalidators.yaml
  config/samples/ocivalidator-private-registry.yaml
  internal/controller/ocivalidator_controller.go
  internal/controller/ocivalidator_controller_test.go
Labels: size:L, lgtm, new-feature

#255 feat: add GetKind to satisfy ValidationRule
  api/v1alpha1/ocivalidator_types.go
  go.mod
  go.sum
Labels: size:S, new-feature

#256 fix!: ensure we only pull artifacts when running full or fast layer validation
  README.md
  api/v1alpha1/ocivalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-oci/crds/validation.spectrocloud.labs_ocivalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_ocivalidators.yaml
  config/samples/ocivalidator-private-registry.yaml
  config/samples/ocivalidator-public-registry.yaml
  internal/controller/ocivalidator_controller_test.go
  pkg/oci/oci.go
  pkg/oci/oci_test.go
  pkg/ociclient/oci_client.go
Labels: bug, size:L, lgtm

#252 chore(main): release 0.2.0
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:M, lgtm

#260 chore: only add auth and pubkeys when they're not empty
  internal/controller/ocivalidator_controller.go
Labels: enhancement, size:XS, lgtm

#268 fix: support private ecr registry validation with a per rule aws env vars
  internal/controller/ocivalidator_controller.go
  pkg/constants/constants.go
  pkg/validate/validate.go
Labels: bug, size:M, lgtm

#259 chore(main): release 0.2.1
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:M, lgtm

#270 feat!: enforce that at least 1 artifact is added to the OciRegistryRule
  api/v1alpha1/ocivalidator_types.go
  chart/validator-plugin-oci/crds/validation.spectrocloud.labs_ocivalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_ocivalidators.yaml
  config/samples/ocivalidator-private-registry.yaml
  pkg/oci/oci.go
  pkg/oci/oci_test.go
Labels: enhancement, size:L, lgtm

#273 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/ocivalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
Labels: enhancement, size:S, lgtm

#271 chore(main): release 0.3.0
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:M, new-feature

#276 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/ocivalidator_types.go
Labels: bug, size:XS

#275 chore: assert that PluginSpec is implemented
  api/v1alpha1/ocivalidator_types.go
  go.mod
  go.sum
Labels: enhancement, size:XS, lgtm

#278 chore(main): release 0.3.1
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: bug, autorelease: pending, size:S

#283 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/ocivalidator_types.go
Labels: bug, size:XS

#282 chore(main): release 0.3.2
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-oci/Chart.yaml
  chart/validator-plugin-oci/README.md
  chart/validator-plugin-oci/values.yaml
Labels: autorelease: pending, size:S
